controllers:
    config:
        body:
            control_type: thruster  # cannot be wrench anyway because of vectored thrusters
            state: state
            command: body_command
            cascaded_position: False
            dynamic_reconfigure: True
    x:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}
    y:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}
    z:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}
    pitch:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100} 
    roll:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}
    yaw:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}

