<?xml version="1.0"?>

<!-- STL-version of the URDF, used with gazebo for dynamic simulation  -->

<robot name="barco_auv" xmlns:xacro="http://www.ros.org/wiki/xacro">
      <material name="blue">
        <color rgba="0 0 .8 1"/>
      </material>
    
    <xacro:property name="PI" value="3.1415926535897931"/>
    
    <!-- Body properties -->
    <xacro:property name="body_mass" value="10"/>
    <xacro:property name="body_radius" value="0.13"/>
    <xacro:property name="body_length" value="1.5" />
    <xacro:property name="X_cog" value="${-0.5*body_radius}" />
    
    <!-- thrusters -->
    <xacro:property name="tr1" value=".02" />
    <xacro:property name="tl1" value=".1" />
    <xacro:property name="tr2" value=".05" />
    <xacro:property name="tl2" value=".03" />
    
    <xacro:property name="eps" value="0.00000001"/>
    
    <!-- Thruster link -->
    <xacro:macro name="thruster_link" params="name xyz rpy">
        
        <joint name="${name}_link" type="revolute">
            <parent link="base_link"/>
            <child link="${name}"/>
            <origin rpy="${rpy}" xyz="${xyz}"/>
            <dynamics damping="10.0"/>
            <axis xyz="0 1 0"/>
            <limit effort="30" velocity="5.0" lower="-${PI/2}" upper="${PI/2}" />
        </joint>
        
        <link name="${name}">      
            <buoyancy><compensation>1.0</compensation></buoyancy>
            <visual name="${name}_1">
                <geometry>
                    <cylinder length="${tl1}" radius="${tr1}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
            </visual>  
            <visual name="${name}_2">
                <origin xyz="0 0 ${(tl1+tl2)/2}"/>
                <geometry>
                    <cylinder length="${tl2}" radius="${tr2}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
                
            </visual>  
            <inertial>
                <mass value="0.1"/>
                <inertia
                    ixx="0.01"
                    ixy="0.0"
                    ixz="0.0"
                    iyy="0.01"
                    iyz="0.0"
                    izz="0.01"/>
                </inertial>  
            </link>                 
            
            <gazebo reference="${name}">
                <material>Gazebo/Black</material>
            </gazebo>
        </xacro:macro>                   
        
        <link name="base_link">
            <visual>
                <origin rpy="${PI/2} 0 ${PI/2}"/>
                <geometry>
                    <mesh filename="file://$(env HOME)/.uwsim/data/robot/barco/pt90.stl"/>
                </geometry>
                      <material name="blue"/>
            </visual>
            <collision>
                <origin rpy="${PI/2} 0 ${PI/2}"/>
                <geometry>
                    <mesh filename="file://$(env HOME)/.uwsim/data/robot/barco/pt90.stl"/>
                </geometry>
                      <material name="blue"/>
            </collision>
            <inertial>
                <origin xyz="0 0 ${X_cog}" rpy="0 ${-PI/2} 0"/>
                <mass value="${body_mass}"/>
                <inertia
                    ixx="${body_mass*(body_radius*body_radius/4+body_length*body_length/12)}"
                    ixy="0.0"
                    ixz="0.0"
                    iyy="${body_mass*(body_radius*body_radius/4+body_length*body_length/12)}"
                    iyz="0.0"
                    izz="${body_mass*body_radius*body_radius/2}"/>
                </inertial>  
                
                <buoyancy>
                    <compensation>1.2</compensation>
                    <origin xyz= "0 0 0"/>
                    <limit radius="${body_radius}"/>
                    <damping xyz="20 50 50" rpy="20 50 50"/>
                </buoyancy>               
            </link>

	<link name="rudder">
		<inertial>
			<mass value="0.05" />

			<inertia
			  ixx="0.05"
			  ixy="0.0"
			  iyy="0.05"
			  ixz="0.0"
			  iyz="0.0"
			  izz="0.005"/>
		</inertial>

	      <collision name="collision">
		<geometry>
		  <box size="0.1 0.02 0.3" />
		</geometry>
		<origin rpy="0 0 0" xyz="-0.1 0 0"/>
	      </collision>

	      <visual name="visual">
		<geometry>
		  <box size="0.1 0.02 0.3" />
		</geometry>
		<origin rpy="0 0 0" xyz="-0.1 0 0"/>
	      </visual>
	</link>

       <joint name="rudder_joint" type="revolute">
            <parent link="base_link"/>
            <child link="rudder"/>
            <origin rpy="0 0 0" xyz="-0.53 0 -0.1"/>
            <dynamics damping="1.0"/>
            <axis xyz="0 0 1"/>
            <limit effort="50" velocity="5" lower="-${PI/3}" upper="${PI/3}" />
        </joint>

<!-- Plugin list -->
        <gazebo>
            <!-- Gazebo plugin listens to the body-->
		 <plugin name="LiftDrag" filename="libLiftDragPlugin.so"> 
		<!--<plugin name="LiftDrag" filename="libliftdragww.so">-->

			<a0>0</a0>
			<cla>0.752798721</cla>
			<cda>0.3417112299</cda>
			<!--
			<cma>-1.8</cma> momentum
			<cma_stall>0</cma_stall>
			-->
			<alpha_stall>0.785</alpha_stall>
			<cla_stall>-0.85</cla_stall>
			<cda_stall>-0.3233984055</cda_stall>
			
			<cp>-0.5 0 0</cp>
			<area>0.03</area>
			<air_density>1000</air_density>
			<forward>1 0 0</forward>
			<upward>0 1 0</upward>
<link_name>rudder</link_name>
	      </plugin>

<plugin name="freefloating_gazebo_control" filename="libfreefloating_gazebo_control.so">
                <switchService>switch</switchService>
                <updateRate>100</updateRate>
                <link>base_link</link>

                <!--    these two thrusters are actually orientable, so the map should not be hard-coded 
                        the thruster name is the name of the corresponding link --> 
                <thruster>
                    <effort>30</effort>
                    <name>fwd</name>
                </thruster>
                
                <!-- these thrusters are fixed and the map can be hard-coded 
                     they will be given a name (thr2 to thr4)  --> 
     
            </plugin>

        </gazebo>  
            
    <!-- Define two steering thrusters, with assumed force control in Z-direction -->
    <xacro:thruster_link name="fwd" xyz="-0.52 0 -0.03" rpy="0 ${-PI/2} 0"/>
    
    <xacro:macro name="thruster_dummy_link" params="name xyz rpy">        
        <joint name="${name}" type="fixed">
            <parent link="base_link"/>
            <child link="${name}"/>
            <origin rpy="${rpy}" xyz="${xyz}"/>
        </joint>
        <link name="${name}"/>
    </xacro:macro>  
        
    <!-- Dummy links to display wrench in Rviz, autogenerated -->
    <!-- <xacro:thruster_dummy_link name="thr2" xyz="0.0 0.0 0.0" rpy="1.57079632679 -0.0 0.0"/>
    <xacro:thruster_dummy_link name="thr3" xyz="-0.45 0.0 0.0" rpy="0.0 -0.0 0.0"/>
    <xacro:thruster_dummy_link name="thr4" xyz="0.45 0.0 0.0" rpy="0.0 -0.0 0.0"/>-->
            
</robot>
